[build-system]
build-backend = "maturin"
dependencies = ["flask~=1.1.0", "toml==0.10.0"]
requires = ["maturin>=0.13,<0.14"]

[project]
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []
description = "Probably the fastest Python package to convert longitude/latitude to timezone name"
name = "tzfpy"
requires-python = ">=3.7"

[project.optional-dependencies]
pytz = [
  "pytz==2022.7.1",
]

[project.urls]
Documentation = "https://github.com/ringsaturn/tzfpy"
Issues = "https://github.com/ringsaturn/tzfpy/issues"
"Source Code" = "https://github.com/ringsaturn/tzfpy"
