name: Bench

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: tzfpy
      BENCHER_TESTBED: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - uses: bencherdev/bencher@main
      - name: Install tzfpy and test
        shell: bash
        run: |
          make sync
          source .venv/bin/activate
          bencher run \
            --file results.json \
            --branch "$GITHUB_REF_NAME" \
            --token "${{ secrets.BENCHER_API_TOKEN }}" \
            --adapter python_pytest \
            --err \
            "pytest --benchmark-json results.json --benchmark-warmup=on --benchmark-warmup-iterations=100 tests/test_bench.py"
