name: Bench

on:
  push:
    branches:
      - main

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: tzfpy
      BENCHER_TESTBED: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: bencherdev/bencher@main
      - name: Install tzfpy and test
        shell: bash
        run: |
          uv sync
          source .venv/bin/activate
          bencher run \
            --file results.json \
            --branch "$GITHUB_REF_NAME" \
            --token "${{ secrets.BENCHER_API_TOKEN }}" \
            --adapter python_pytest \
            --err \
            "pytest --benchmark-json results.json tests/test_bench.py"
