name: Bench

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  UV_CACHE_DIR: "/tmp/.uv-cache"

jobs:
  benchmark_with_bencher:
    name: Continuous Benchmarking with Bencher
    runs-on: ubuntu-latest
    env:
      BENCHER_PROJECT: tzfpy
      BENCHER_TESTBED: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - uses: bencherdev/bencher@main
      - name: Install tzfpy and test
        shell: bash
        run: |
          uv sync
          source .venv/bin/activate
          bencher run \
            --file results.json \
            --branch "$GITHUB_REF_NAME" \
            --token "${{ secrets.BENCHER_API_TOKEN }}" \
            --adapter python_pytest \
            --err \
            "pytest --benchmark-json results.json tests/test_bench.py"

  benchmark_with_codspeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install
        run: |
          uv build --config-setting profile==profiling

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: uv run pytest tests/ --codspeed

      - name: Minimize uv cache
        run: uv cache prune --ci
