name: Bench

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  UV_CACHE_DIR: "/tmp/.uv-cache"

jobs:
  benchmark_with_codspeed:
    name: Continuous Benchmarking with CodSpeed
    runs-on: ubuntu-latest
    steps:
      - name: Collect Workflow Telemetry
        uses: runforesight/workflow-telemetry-action@v2
        with:
          comment_on_pr: false
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install
        run: |
          uv build --config-setting profile==profiling

      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          run: uv run pytest tests/ --codspeed

      - name: Minimize uv cache
        run: uv cache prune --ci
