name: Test

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Testing:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2022-12-20

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: "requirements_dev.txt"

      - name: Create virtual environment
        run: |
          python -m venv venv

      - name: Install tzfpy and test(not windows)
        if: matrix.os != 'windows-latest'
        run: |
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements_dev.txt
          maturin develop
          pytest --cov

      - name: Install tzfpy and test(windows)
        if: matrix.os == 'windows-latest'
        run: |
          . venv\Scripts\activate.bat
          python -m pip install --upgrade pip
          python -m pip install -r requirements_dev.txt
          maturin develop
          pytest --cov
